### ISSUE TITLE
Search service backup

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-search-lucene29#2]
## Goal
Letting operators create a backup of a centralized index **without downtime**.

## Proposed solution
Create a backup snapshot of the index, without pause or duplicated index folders.

0. The service is started, there is a single index directory.
1. A StartBackup request arrives to the service.
2. Current index operations should finish in the current folder.
3. Open a new temp index folder (partial), new write operations work there.
4. Old directory is copied (LocalIndex_backup_timestamp)
5. Merge temp folder to old one. (Lucene api?)
6. Reopen old folder and continue writing there.
7. Delete temp folder (if lucene doesn't delete it itself)

A new api should also provide backup info (last backup, current status).

**Comment by tusmester** [comment]
@kavics please take a look.

**Comment by kavics** [comment]
There are some questions for me:
- I don't know whether the old folder is copyable when a reader uses it for queries.
- How to do the index merging?
- Do we need to stop indexing and querying during the merge process?
- How long the merge process in case of the big index and a small one.
